#!/bin/bash

##########################################################################
# For SleepWatcher to work, you will need to write sleep and
# wakeup scripts, located here when using brew services:
# 
#   ~/.sleep
#   ~/.wakeup
# 
# To restart sleepwatcher after an upgrade:
#   brew services restart sleepwatcher
# Or, if you don't want/need a background service you can just run:
#   /opt/homebrew/opt/sleepwatcher/sbin/sleepwatcher -V -s /Users/jabriel/.sleep -w /Users/jabriel/.wakeup
##########################################################################
start=$SECONDS

APP_NAME="BetterDummy"
APP_LOC="/Applications/BetterDisplay.app"

# Check if the application is running
if pgrep $APP_NAME > /dev/null
then
    # If it is running, obtain its PID and terminate it
    PID=$(pgrep $APP_NAME)
    while [[ $[$SECONDS - start] < 5 ]]; do
      echo 'wait for 5 seconds' > /dev/null
    done
    kill $PID
    # Wait for the process to terminate
    while pgrep -u $UID -x $APP_NAME >/dev/null; do sleep 1; done
else
  echo "$APP_NAME is not running."
fi
